### ISSUE TITLE
Victim of Fire/Trauma Research Plan

### ISSUE THREAD

**Issue by hilaryhb** [cagov/UX#20]
As a survivor of a wildfire, I need find state opportunities so that I can rebuild my life

- [x] Meet w Angie 12/17 to talk about how to recruit

- [x] Call orgs and businesses in Paradise to schedule 1/29 

- [x] Design field research day

- [x] Hold 1 hr journey session

- [x] Field research day Jan 29

**Comment by abquirarte** [comment]
Met with Brian F from OES on 1/2
Followed up with options and next steps 1/6 (and sent a couple of nudges/calls since then):


- What kind of questions are your PIOs getting around recovery and preparedness? 
- Can we get the Mayor of Paradise help us identify 3-4 people that we can meet with?
- You mentioned you had some polls? Is that something you could share with us?
- Should we connect with Justin and Karen on the Listos effort? At least if they can share any background documents. 
- It would be helpful to get a high level overview of State Emergency Operations for Rebecca and Hilary. Perhaps you (or someone) can walk us through what that entails? For example, what happens where there is a statewide emergency declaration? How does OES coordinate with various entities and across jurisdictions?
- you mentioned 15% of people are signed up for alerts. Which alerts are you referring to? We found a few in our research so far. :)

**Comment by abquirarte** [comment]
Notes from visit: https://docs.google.com/document/d/1BJ_R_pt0gTq2aovmNNhWTr9U2Og7Kq3KNuIzUjacXXE/edit?ts=5e30bb2a#
