### ISSUE TITLE
UX prototype: Apply for Apply for a Cal Grant 

### ISSUE THREAD

**Issue by artuoma** [cagov/UX#83]
**Parent User Story:** https://github.com/cagov/UX/issues/35
**Prototype Link(s):** https://cagov.github.io/UX/cal-grant/

- [x] HTML page(s) created and linked in UX repo
- [x] Meta description added 
- [x] Page title updated
- [x] Content integrated according to design system and standards 
- [x] Automated accessibility checks performed (score of 100%)
- [x] Manual accessibility checks performed ([See checklist](https://drive.google.com/open?id=0B72FqFUONAggazJwQURQeTBPMEZGRjJXSFNGcDJrMF9ENERR))
- [x] HTML structure verified
- [x] Design issue template # (Closed)
- [ ] Migrated to Alpha repo
- [x] 2nd pair of eyes- Oriel, others

**11y Status:** Issues and resolution status if applicable

**Design Issue Link:** Link to Design issue if applicable#
- https://github.com/cagov/UX/issues/85

**Comment by lukefretwell** [comment]
Comments:

* .lead really should be first item on the page before any header tags not h1. (To me this is the lead: 'A Cal Grant is money for college you don’t have to pay back.'). In this page, the description of the service is out of context (below 'Apply for a Cal Grant in two steps'). I'd also not list how many steps unless we're going to do that everywhere. 
* List is indented on this page (but not others) so can't tell if it's a CSS issue or not coded correctly.
* Should the h1 title be 'Apply for college financial aid (Cal Grant)' per our convo about brands?
* I'd suggest not using an accordion if there's just one.

**Comment by humancenteredhuman** [comment]
-That might make sense to move up 'A Cal Grant is money for college you don’t have to pay back,' but I'll defer to you two on the lead class question. 
-Students did appreciate the callout for "Apply in two steps" because it sounded easy, but we can keep it consistent with "Steps to..." 
-After user feedback, @hilaryhb and I agreed it would be best to change the headline from "Apply for college financial aid" to the current "Apply for a Cal Grant (college financial aid)." The former sounded too broad, like a guide to all of the types of financial aid that exist. And even putting Cal Grant in parenthesis afterwards would be confusing, I think. 
-Re: the accordion, the idea was to not scare students off from applying because of the long list of eligibility requirements. Even guidance counselors aren't always expected to know those, so I wouldn't want to make students feel like they have to go through the list.

**Comment by abquirarte** [comment]
See lead class section in content style guide: https://docs.google.com/document/d/1YsOO9GL5MXlkVTZ4JQHFefdRwPRgTe_ACNNRsGjs1LI/edit#

**Comment by abquirarte** [comment]
Angie sent a follow-up question to CalGrants SME per @orielgomez 's comments: 

If a student applies for FAFSA and submits their GPA form on Oct. 1, when is the soonest that student can see whether they get a Cal Grant on their WebGrants 4 Students dashboard?
